//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Windows\AppData\Local\Temp\A39F85AA4CDFBC37BD710146F1D63008AF3B\2\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Windows\AppData\Local\Temp\A39F85AA4CDFBC37BD710146F1D63008AF3B\2\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
  
    ViewBag.Title = "Categories";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";


#line default
#line hidden

#line 3 "C:\Users\Windows\AppData\Local\Temp\A39F85AA4CDFBC37BD710146F1D63008AF3B\2\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
   __o = Html.ActionLink("TẠO MỚI", "Create", null, new
        {
            @class = "btn btn-primary"
       });


#line default
#line hidden

#line 4 "C:\Users\Windows\AppData\Local\Temp\A39F85AA4CDFBC37BD710146F1D63008AF3B\2\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
        foreach (var item in Model)
        {
            

#line default
#line hidden

#line 5 "C:\Users\Windows\AppData\Local\Temp\A39F85AA4CDFBC37BD710146F1D63008AF3B\2\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
               __o = Html.DisplayFor(modelItem => item.IDCate);


#line default
#line hidden

#line 6 "C:\Users\Windows\AppData\Local\Temp\A39F85AA4CDFBC37BD710146F1D63008AF3B\2\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
               __o = Html.DisplayFor(modelItem => item.NameCate);


#line default
#line hidden

#line 7 "C:\Users\Windows\AppData\Local\Temp\A39F85AA4CDFBC37BD710146F1D63008AF3B\2\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
               __o = Html.ActionLink("Sửa", "Edit", new { id = item.ID }, new
                    {
                   @class = "btn btn-success"
                    });


#line default
#line hidden

#line 8 "C:\Users\Windows\AppData\Local\Temp\A39F85AA4CDFBC37BD710146F1D63008AF3B\2\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
               __o = Html.ActionLink("Chi tiết", "Details", new { id = item.ID },
                   new { @class = "btn btn-primary" });


#line default
#line hidden

#line 9 "C:\Users\Windows\AppData\Local\Temp\A39F85AA4CDFBC37BD710146F1D63008AF3B\2\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
               __o = Html.ActionLink("Xóa", "Delete", new { id = item.ID }, new
                    {
                   @class = "btn btn-danger"
                    });


#line default
#line hidden

#line 10 "C:\Users\Windows\AppData\Local\Temp\A39F85AA4CDFBC37BD710146F1D63008AF3B\2\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
                 
        }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\6\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\6\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
  
    ViewBag.Title = "Categories";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";


#line default
#line hidden

#line 3 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\6\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
   __o = Html.ActionLink("TẠO MỚI", "Create", null, new
        {
            @class = "btn btn-primary"
       });


#line default
#line hidden

#line 4 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\6\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
        foreach (var item in Model)
        {
            

#line default
#line hidden

#line 5 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\6\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
               __o = Html.DisplayFor(modelItem => item.IDCate);


#line default
#line hidden

#line 6 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\6\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
               __o = Html.DisplayFor(modelItem => item.NameCate);


#line default
#line hidden

#line 7 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\6\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
               __o = Html.ActionLink("Sửa", "Edit", new { id = item.ID }, new
                    {
                   @class = "btn btn-success"
                    });


#line default
#line hidden

#line 8 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\6\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
               __o = Html.ActionLink("Chi tiết", "Details", new { id = item.ID },
                   new { @class = "btn btn-primary" });


#line default
#line hidden

#line 9 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\6\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
               __o = Html.ActionLink("Xóa", "Delete", new { id = item.ID }, new
                    {
                   @class = "btn btn-danger"
                    });


#line default
#line hidden

#line 10 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\6\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
                 
        }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\5\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\5\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
  
    ViewBag.Title = "Categories";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";


#line default
#line hidden

#line 3 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\5\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
   __o = Html.ActionLink("TẠO MỚI", "Create", null, new
        {
            @class = "btn btn-primary"
       });


#line default
#line hidden

#line 4 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\5\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
        foreach (var item in Model)
        {
            

#line default
#line hidden

#line 5 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\5\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
               __o = Html.DisplayFor(modelItem => item.IDCate);


#line default
#line hidden

#line 6 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\5\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
               __o = Html.DisplayFor(modelItem => item.NameCate);


#line default
#line hidden

#line 7 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\5\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
               __o = Html.ActionLink("Sửa", "Edit", new { id = item.ID }, new
                    {
                   @class = "btn btn-success"
                    });


#line default
#line hidden

#line 8 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\5\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
               __o = Html.ActionLink("Chi tiết", "Details", new { id = item.ID },
                   new { @class = "btn btn-primary" });


#line default
#line hidden

#line 9 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\5\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
               __o = Html.ActionLink("Xóa", "Delete", new { id = item.ID }, new
                    {
                   @class = "btn btn-danger"
                    });


#line default
#line hidden

#line 10 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\5\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
                 
        }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\4\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\4\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
  
    ViewBag.Title = "Categories";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";


#line default
#line hidden

#line 3 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\4\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
   __o = Html.ActionLink("TẠO MỚI", "Create", null, new
        {
            @class = "btn btn-primary"
       });


#line default
#line hidden

#line 4 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\4\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
        foreach (var item in Model)
        {
            

#line default
#line hidden

#line 5 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\4\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
               __o = Html.DisplayFor(modelItem => item.IDCate);


#line default
#line hidden

#line 6 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\4\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
               __o = Html.DisplayFor(modelItem => item.NameCate);


#line default
#line hidden

#line 7 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\4\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
               __o = Html.ActionLink("Sửa", "Edit", new { id = item.ID }, new
                    {
                   @class = "btn btn-success"
                    });


#line default
#line hidden

#line 8 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\4\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
               __o = Html.ActionLink("Chi tiết", "Details", new { id = item.ID },
                   new { @class = "btn btn-primary" });


#line default
#line hidden

#line 9 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\4\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
               __o = Html.ActionLink("Xóa", "Delete", new { id = item.ID }, new
                    {
                   @class = "btn btn-danger"
                    });


#line default
#line hidden

#line 10 "C:\Users\Windows\AppData\Local\Temp\88DE697227C5E09663CE7ECD8CDC1698A05C\4\DigitalHub\DigitalHub\Views\Categories\Index.cshtml"
                 
        }

#line default
#line hidden
}
}
}
